version: '3.8'

services:
  consul-server-1:
    image: consul:1.15.4
    container_name: consul-server-1
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_SERVER=1
      - CONSUL_BOOTSTRAP_EXPECT=3
    restart: unless-stopped

  consul-server-2:
    image: consul:1.15.4
    container_name: consul-server-2
    ports:
      - "8501:8500"
      - "8601:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_SERVER=1
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_JOIN=consul-server-1
    restart: unless-stopped

  consul-server-3:
    image: consul:1.15.4
    container_name: consul-server-3
    ports:
      - "8502:8500"
      - "8602:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_SERVER=1
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_JOIN=consul-server-1
    restart: unless-stopped
