version: '3.7'

services:
  redpanda-1:
    image: redpandadata/redpanda:v23.2.16
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda-1:29092,OUTSIDE://localhost:9092
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda-1:33145
    ports:
      - 9092:9092
      - 29092:29092
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true'"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - redpanda_network

  redpanda-2:
    image: redpandadata/redpanda:v23.2.16
    container_name: redpanda-2
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 1
      - --kafka-addr PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr PLAINTEXT://redpanda-2:29093,OUTSIDE://localhost:9093
      - --rpc-addr 0.0.0.0:33146
      - --advertise-rpc-addr redpanda-2:33146
      - --seeds redpanda-1:33145
    ports:
      - 9093:9093
      - 29093:29093
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true'"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - redpanda_network

  redpanda-3:
    image: redpandadata/redpanda:v23.2.16
    container_name: redpanda-3
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 2
      - --kafka-addr PLAINTEXT://0.0.0.0:29094,OUTSIDE://0.0.0.0:9094
      - --advertise-kafka-addr PLAINTEXT://redpanda-3:29094,OUTSIDE://localhost:9094
      - --rpc-addr 0.0.0.0:33147
      - --advertise-rpc-addr redpanda-3:33147
      - --seeds redpanda-1:33145
    ports:
      - 9094:9094
      - 29094:29094
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true'"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - redpanda_network

  redpanda-console:
    image: redpandadata/console:v2.3.3
    container_name: redpanda-console
    depends_on:
      - redpanda-1
      - redpanda-2
      - redpanda-3
    ports:
      - 8080:8080
    environment:
      KAFKA_BROKERS: "redpanda-1:29092,redpanda-2:29093,redpanda-3:29094"
      REDPANDA_ADMIN_API_ENABLED: "true"
      REDPANDA_ADMIN_API_URLS: "http://redpanda-1:9644,http://redpanda-2:9644,http://redpanda-3:9644"
      SCHEMA_REGISTRY_ENABLED: "true"
      SCHEMA_REGISTRY_URLS: "http://redpanda-1:8081,http://redpanda-2:8081,http://redpanda-3:8081"
    networks:
      - redpanda_network

networks:
  redpanda_network:
    name: redpanda_network