version: 1
packages:
  - path: "../internal/generated/repository"
    name: "db"
    engine: "postgresql"
    schema: "../db/postgres/factories/"
    queries: "../db/postgres/queries/"
    sql_package: "pgx/v4"
    emit_empty_slices: true
    emit_json_tags: true
    json_tags_case_style: "snake"
overrides:
  - db_type: "uuid"
    go_type: "github.com/google/uuid.UUID"
    nullable: true