version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-demo
    ports:
      - "8123:8123"     # HTTP interface (browser/curl)
      - "9000:9000"     # Native client (clickhouse-client)
      - "9009:9009"     # TCP inter-server communication
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=datasets
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
