version: '3'
services:
  clickhouse-server:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse_server
    restart: always
    ports:
      - "8123:8123"   # HTTP interface for querying ClickHouse
      - "9000:9000"   # Native TCP protocol for client applications (like Go apps)
      - "9009:9009"   # Insecure native TCP protocol
    volumes:
#      - ./custom-config/config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_data:/var/lib/clickhouse  # Persist data in a Docker volume
    environment:
      - TZ=UTC  # Time-zone settings (optional, adjust to your needs)

volumes:
  clickhouse_data: