server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: go-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: go-app
          app: my-go-app
          environment: dev
          __path__: /var/log/app.log

    pipeline_stages:
      - regex:
          expression: '(?P<level>INFO|ERROR|DEBUG|WARN): (?P<message>.*)'
      - labels:
          level:
      - output:
          source: message
